SystemOrganization addCategory: #'Voyage-Mongo-Core'!
SystemOrganization addCategory: #'Voyage-Mongo-Core-Base'!
SystemOrganization addCategory: #'Voyage-Mongo-Core-Exceptions'!
SystemOrganization addCategory: #'Voyage-Mongo-Core-Magritte'!
SystemOrganization addCategory: #'Voyage-Mongo-Core-Operations'!
SystemOrganization addCategory: #'Voyage-Mongo-Core-Pooling'!
SystemOrganization addCategory: #'Voyage-Mongo-Core-Utilities'!
