SystemOrganization addCategory: #'Voyage-Mongo-Core'!
SystemOrganization addCategory: 'Voyage-Mongo-Core-Base'!
SystemOrganization addCategory: 'Voyage-Mongo-Core-Caching'!
SystemOrganization addCategory: 'Voyage-Mongo-Core-Exceptions'!
SystemOrganization addCategory: 'Voyage-Mongo-Core-Pooling'!
SystemOrganization addCategory: 'Voyage-Mongo-Core-Utilities'!
SystemOrganization addCategory: 'Voyage-Mongo-Core-WriteStrategy'!
