SystemOrganization addCategory: #'Voyage-Mongo-Tests'!
SystemOrganization addCategory: 'Voyage-Mongo-Tests-Base'!
SystemOrganization addCategory: 'Voyage-Mongo-Tests-Data'!
SystemOrganization addCategory: 'Voyage-Mongo-Tests-Replication'!
SystemOrganization addCategory: 'Voyage-Mongo-Tests-Resources'!
SystemOrganization addCategory: 'Voyage-Mongo-Tests-Serialization'!
SystemOrganization addCategory: 'Voyage-Mongo-Tests-Utilities'!
